name: Manual Build and Release of luci-app-nfttl

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g., v1.0.0)'
        required: true
      release_name:
        description: 'Release Name (e.g., luci-app-nfttl v1.0.0)'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-venv rsync unzip zlib1g-dev file wget python3

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-23.05.3-x86-64_*.tar.xz
        mv openwrt-sdk-*/ openwrt-sdk

    - name: Add luci-app-nfttl to feeds.conf
      run: |
        cd openwrt-sdk
        # Add the src-git directive for luci-app-nfttl
        echo "src-git myapp https://github.com/aNzTikTok/luci-app-nfttl.git" >> feeds.conf

    - name: Update and install feeds
      run: |
        cd openwrt-sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build luci-app-nfttl
      run: |
        cd openwrt-sdk
        make defconfig
        make package/luci-app-nfttl/compile V=s

    - name: Find built .ipk
      id: find_ipk
      run: |
        FILE=$(find openwrt-sdk/bin/packages/ -name 'luci-app-nfttl_*.ipk' | head -n 1)
        echo "ipk_path=$FILE" >> "$GITHUB_OUTPUT"

    - name: Create GitHub Release and Upload IPK
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.inputs.release_name }}
        tag_name: ${{ github.event.inputs.release_tag }}
        files: ${{ steps.find_ipk.outputs.ipk_path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
